name: nf-core-bactmap-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc=0.11.8
  - multiqc=1.6
  - bwa=0.7.17
  - samtools=1.9
  - bcftools=1.9
  - trimmomatic=0.38
  - mash=2.1
  - seqtk=1.3
  - pysam=0.15.0
  - biopython=1.72
  - iqtree=1.6.8
  - snp-sites=2.4.1
  - gubbins=2.3.4
  - fasttree=2.1.10
  - enabrowsertools=1.5.4